/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/health": {
    get: operations["HealthController_check"];
  };
  "/ready": {
    get: operations["HealthController_ready"];
  };
  "/live": {
    get: operations["HealthController_live"];
  };
  "/platforms": {
    get: operations["PlatformController_findAll"];
    post: operations["PlatformController_create"];
  };
  "/platforms/{id}": {
    get: operations["PlatformController_findOne"];
    delete: operations["PlatformController_remove"];
    patch: operations["PlatformController_update"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  HealthController_check: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  HealthController_ready: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  HealthController_live: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  PlatformController_findAll: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  PlatformController_create: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  PlatformController_findOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  PlatformController_remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  PlatformController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
}
