name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm turbo build
      - run: pnpm test
      - run: pnpm --filter @gamearr/web test -- --coverage
      - uses: codecov/codecov-action@v4
        with:
          files: apps/web/coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
      - name: Build Docker images
        if: github.ref == 'refs/heads/main'
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          DATA_ROOT: ./data
        run: docker compose -f infra/docker-compose.yml -f docker-compose.app.yml build
